### PR TITLE
[CMake][CI] Allow to build DatabaseExplorer plugin with mariaDb (mysql)

### PR DESCRIPTION
**Pull request by Jarod42**
Compile DatabaseExplorer with mysql (mariaDb) enabled by default (but MacOS which default to OFF).

Note: I cannot test behavior for Ubuntu/MacOS.
I did minimal checks on minGW (connect to empty DB).

### CODE REVIEW

**Comment by eifrah-aws** [comment]
The problem with macOS is not installing the libraries is actually the packaging process. Atm, when compiling and packaging for macOS, `/opt/homebrew` is not in the PATH (on purpose) - no all mac users are using `brew` (some are using `The MacPorts Project`). So we can't really install binaries from `/opt/homebrew`. My suggestion: make this optional on macOS until I will figure the packaging stuff on macOS

**Comment by eranif** [comment]
The problem with macOS is not installing the libraries is actually the packaging process. Atm, when compiling and packaging for macOS, `/opt/homebrew` is not in the PATH (on purpose) - no all mac users are using `brew` (some are using `The MacPorts Project`). So we can't really install binaries from `/opt/homebrew`. My suggestion: make this optional on macOS until I will figure the packaging stuff on macOS

**Comment by Jarod42** [comment]
Unsure to understand what you mean,
with `option(WITH_MYSQL "Enable support of MySQL for DatabaseExplorer plugin" ON)`
user might disable it...

**Comment by eifrah-aws** [comment]
> Unsure to understand what you mean, with `option(WITH_MYSQL "Enable support of MySQL for DatabaseExplorer plugin" ON)` user might disable it...

The default should be `OFF`.
we could also change it to:


```cmake
if (APPLE)
    option(WITH_MYSQL "Enable support of MySQL for DatabaseExplorer plugin" OFF)
else ()
    option(WITH_MYSQL "Enable support of MySQL for DatabaseExplorer plugin" ON)
endif ()
```

**Comment by eranif** [comment]
> Unsure to understand what you mean, with `option(WITH_MYSQL "Enable support of MySQL for DatabaseExplorer plugin" ON)` user might disable it...

The default should be `OFF`.
we could also change it to:


```cmake
if (APPLE)
    option(WITH_MYSQL "Enable support of MySQL for DatabaseExplorer plugin" OFF)
else ()
    option(WITH_MYSQL "Enable support of MySQL for DatabaseExplorer plugin" ON)
endif ()
```

**Pull request merged**
