### PR TITLE
Use /bin/sh instead of /bin/bash.

### PR DESCRIPTION
**Pull request by rozhuk-im**
Not all systems have bash installed, and it does not required to CodeLite work.

### CODE REVIEW

**Comment by rozhuk-im** [comment]
ping

**Comment by eranif** [comment]
Note that this PR can't be merged due to conflicts

**Comment by rozhuk-im** [comment]
Is ok now?

**Comment by rozhuk-im** [comment]
ping

**Comment by rozhuk-im** [comment]
Thanks!

**Pull request merged**
