### PR TITLE
Line copy/cut feature

### PR DESCRIPTION
**Pull request by nghiaho12**
I miss the ability to copy and cut line, which is present in Geany and CodeBlocks.

### CODE REVIEW

**Comment by eranif** [comment]
IIRC, `Ctrl-C` with no selection, copies the entire line
Doesn't this works for you?

**Comment by nghiaho12** [comment]
Oh, I had no idea that even worked!

**Comment by nghiaho12** [comment]
Cut line is still useful.

**Comment by eranif** [comment]
Having a dedicated keyboard shortcut for this is a good idea, so we can keep both functionalities.
In fact, having this as a menu entry in the menu will expose people to this functionality

**Comment by sausagejohnson** [comment]
@eranif  I'd like to revisit this issue if possible. Is it possible to simply have one keyboard shortcut that works like this for both situations:

* For control-X and there is nothing selected, the whole line will be cut to the clipboard
* For control-X and there is text selected, the selected text will be cut to the clipboard
* For control-C and there is nothing selected, the whole line will be copied to the clipboard
* For control-C and there is text selected, the selected text will be copiedto the clipboard

**Pull request merged**
