### PR TITLE
Move some files in sub directories

### PR DESCRIPTION
**Pull request by Jarod42**

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]
I especially appreciate the cleanup done to the includes :+1:

Looks like line endings where also fixed in a couple of files which actually accounts for the majority of diff in the PR.

**Comment by Eric-01** [comment]
In fact, I think it would be a good idea to run ClangFormat (and perhaps other formatters for other languages) on the entire codebase in one single commit, so that future commits don't contain 5 intended changes and 50 completely unrelated formatting improvements here and there made on the user's behalf by the formatter.

Other than that, I really appreciate the work you put into this project, as someone who hasn't contributed any new features or even bug fixes myself. Eranif can't keep up with everything (as seen in the delay when reviewing and merging pull requests), and you're doing a really good job 👍

**Comment by Eric-01** [comment]
Actually, I think it would be a good idea to run ClangFormat (and perhaps other formatters for other languages) on the entire codebase in one single commit, so that future commits don't contain 5 intended changes and 50 completely unrelated formatting improvements here and there made on the user's behalf by the formatter.

Other than that, I really appreciate the work you put into this project, as someone who hasn't contributed any new features or even bug fixes myself. Eranif can't keep up with everything (as seen in the delay when reviewing and merging pull requests), and you're doing a really good job 👍

**Comment by Eric-01** [comment]
Actually, I think it would be a good idea to run ClangFormat (and perhaps other formatters for other languages as well) on the entire codebase in one single commit, so that future commits don't contain 5 intended changes and 50 completely unrelated formatting improvements here and there made on the user's behalf by the formatter.

Other than that, I really appreciate the work you put into this project, as someone who hasn't contributed any new features or even bug fixes myself and just uses CodeLite for my own needs. Eranif can't keep up with everything (as seen in the delay when reviewing and merging pull requests), and you're doing a really good job 👍

**Pull request merged**
