### PR TITLE
Add mingw pch in cmake files

### PR DESCRIPTION
**Pull request by stahta01**

### CODE REVIEW

**Comment by eranif** [comment]
can we remove the `cmake_minimum_required` from all the files and keep it in the main `CMakeLists.txt` file only?

**Comment by stahta01** [comment]
> can we remove the `cmake_minimum_required` from all the files and keep it in the main `CMakeLists.txt` file only?

I have no idea; I thought cmake_minimum_required was required.

Tim S.

**Comment by eranif** [comment]
This change seems to be problematic..
it fails to build on Ubuntu 18.04 :/

**Comment by eranif** [comment]
https://app.circleci.com/pipelines/github/eranif/codelite/1182/workflows/7866461e-ff20-49b7-85ce-e4746c813385/jobs/1173

**Comment by stahta01** [comment]
> This change seems to be problematic..
> it fails to build on Ubuntu 18.04 :/
> can we limit it to MinGW only?

So, you want me to change back to what I had two week ago, okay.
Tim S.

**Comment by eranif** [comment]
sorry about that, I just saw the CI bot failed

**Pull request merged**
