### PR TITLE
Redesign of splashscreen

### PR DESCRIPTION
**Pull request by mrnovvad**
This will be better if someone will change font color of version to white. Sorry for my English

### CODE REVIEW

**Comment by mrnovvad** [comment]
Preview
cl-splash

**Comment by eranif** [comment]
Did you check the updated the splash screen? (the one in your branch is different than the current one)
In your current splash, the "CodeLite" title is not set to "bold" and the background text is too visible
Here is the current git head splash for reference (it is under ./Runtime/images/screenshot.png):

splashscreen

**Comment by RickCHodgin** [comment]
It should also include 2015.

**Comment by mrnovvad** [comment]
Fixed all
cl-splash

**Comment by RickCHodgin** [comment]
FWIW, I like Eran's lighter-color version better than the darker version.  For a splash screen it is more similar to the bright and lively colors of the blue/green/yellow splash screen we're used to seeing.  Maybe there could be an association with the theme such that it is an option, or that lighter themes relate to the lighter splash screen, and darker to the darker... ?

**Comment by mrnovvad** [comment]
"Maybe there could be an association with the theme such that it is an option, or that lighter themes relate to the lighter splash screen, and darker to the darker... ?"
Good idea, but this is a work for programmers

**Comment by RickCHodgin** [comment]
I am a programmer. I'll see about adding it (if it's something that's acceptable to Eran).

**Comment by mrnovvad** [comment]
Cool. Glad to see that my first contribution to the OS is don't being left out :)

**Comment by eranif** [comment]
> "Maybe there could be an association with the theme such that it is an option, or that lighter themes 
> relate to the lighter splash screen, and darker to the darker... ?"
> Good idea, but this is a work for programmers

The problem is that the way I have implemented themes is that it is per file type, i.e. you could have the dark "Dracule" theme for C++ workspace,  while using "Back to school" (green theme) for PHP workspace, or just the default and the workspace loading is determined _after_ the splash screen is shown ...

**Comment by mrnovvad** [comment]
May be this is silly, but is it possible to store last workspace theme in a little single file and load it before splash screen?

**Comment by creatorfromhell** [comment]
>Maybe this is silly, but is it possible to store last workspace theme in a little single file and load it before splash screen?
I feel that this wouldn't be an efficient way to go about this. When you start creating new files just to determine what splash screen to use I begin to question if a new splash screen is even wanted or needed.

**Comment by eranif** [comment]
TBH, I like the current splash screen ... and I really think its a matter if taste here.
In order for this PR to be accepted it should be accompanied with a code that allows the user to select the splash screen (which seems a bit overkill for a splash screen...)

**Pull request closed without merging**
