### PR TITLE
VIM plugin: Added some commands and fixed some bugs

### PR DESCRIPTION
**Pull request by 1123852253**

### CODE REVIEW

**Comment by eranif** [comment]
AFAICS, this won't compile.
For example: the class `LEditor` was renamed to `clEditor`
Please re-base your branch then resubmit it again

Thanks!

**Comment by eranif** [comment]
Closed by mistake ;)

**Comment by 1123852253** [comment]
Renamed class LEditor -> clEditor

**Comment by 1123852253** [comment]
1. Add: file font encoding auto detection
2. Fixed: crash vimCommands
3. Fixed: build error on LinuxMint19

**Pull request merged**
